server:
  port: 10010

spring:
  application:
    name: itcast-zuul
zuul:
  routes:
    service-provider: /service-provider/**
  prefix: /api


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka