server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql:///heima
    username: root
    password: 123456
  application:
    name: service-provider
mybatis:
  type-aliases-package: cn.itcast.service.pojo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: true 
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15